project_name: pr_auto_assign
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    binary: pr_auto_assign
    goos:
      - linux
      - darwin
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format: zip
release:
  prerelease: auto
