project_name: pr-auto-assign
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: pr-auto-assign
    goos:
      - linux
      - darwin
  goarch:
    - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format: zip
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
release:
  prerelease: auto
